docs/UserManual.md

More like fixing a typo, but still ;-)

Fixed spelling error

---

include/civetweb.h
src/civetweb.c

A couple of commits to handle access logging.

Wip log access

---

src/civetweb.c

On Windows, SO_REUSEADDR will happily bind to a socket that is already
in use and the windows-specific SO_EXCLUSIVEADDRUSE is needed instead.
This is defined in winsock2.h.  Defined lean and mean because winsock2
comes in without conflicts that way.

Windows bind() with SO_EXCLUSIVEADDRUSE so that mg_start will fail if socket in use.

---

src/civetweb.c

assert if pointer is NULL

---

src/civetweb.c
src/main.c

This implements a lot of fixes to get MinGW to compile cleanly with high warning levels.
I've tried to make the commits small and the commit messages as descriptive as possible.

MinGW Fixes

---

src/civetweb.c

On Windows, the file creation time can be higher than the modification time.
This can happen for example when a file gets copied.
Since the Last-Modified timestamp is used for caching (i.e. determining whether
a file has changed) it should be based on the most recent timestamp.

Last-Modified timestamp based on creation time

---

test/civetweb_check.h
test/main.c
test/private.c
test/private.h
test/public.c
test/public.h

Updates the license in the new test files

Update test file license

---

test/public_server.c

Conditionnal compilation around use of ws_client3_data. It is defined
only in case of  USE_WEBSOCKET

Compilation Fix

---

examples/websocket_client/Makefile
examples/websocket_client/websocket_client.c
include/civetweb.h
src/civetweb.c

RFC requires that websocket clients mask data.

Add mg_websocket_client_write

---

.gitignore
docs/UserManual.md
src/civetweb.c
src/main.c

Use SSL client certificates to authenticate at the server.
See discussion [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/civetweb/nvBO9EGxpfA/vqdqXaJLBAAJ)

Use SSL client certificates

---

src/civetweb.c

See https://groups.google.com/forum/#!msg/civetweb/nvBO9EGxpfA/fX47X8cUBgAJ

Enable session cache on server side.

---

include/CivetServer.h
src/CivetServer.cpp

https://github.com/civetweb/civetweb/issues/233

CivetServer constructor options as std::vector<std::string>

---

include/CivetServer.h
src/CivetServer.cpp

This adds the ability for a CivetHandler to support the PATCH method

Add PATCH mothod to CivetHandler

---

examples/upload/upload.c
examples/ws_server/Makefile

Typo in example

---

include/CivetServer.h
src/CivetServer.cpp

HEAD request handler for C++ interface

---

src/civetweb.c

The default 40ms TCP socket send delay between REST API responses was the cause of dramatically slower queries-per-second when HTTP 1.1 keep-alive is enabled.  Enabling the TCP_NODELAY socket option on client sockets improved performance by orders of magnitude (~25 requests per second --> ~10000 requests per second).

Add config option for enabling the TCP_NODELAY option on client sockets

---

appveyor.yml

Also, work towards solving #278, but for now only expect more useful information.

Turn on verbose output on failure for tests.

---

include/civetweb.h
src/civetweb.c
src/main.c
src/md5.inl

These showed up from clang on Xcode 7.3.

Fix various const warnings

---

Makefile.osx
src/main.c

I am looking into adding this build to Travis.

Fix OS X dmg build

---

test/CMakeLists.txt

So Windows doesn't need to have the "patch" program.

Apply patch only for OS X

---

src/handle_form.inl

Signed-off-by: Li Peng <lip@dtdream.com>

doc: fix typos

---

src/civetweb.c

These are not so serious. You can put this request off.
(But I especially recommend e071d4691e6b49cee431e16b3d7941cac23c9559 and 51c2afe8f1c582ccb73c0572f1cdebd6b3e44b3a.)

Fix thread handling

---

src/civetweb.c

change mg_get_cookie to ignore substrings

---

src/timer.inl

comparisation
if (ctx->timers->timers[u].time < next_time) {
should be
if (ctx->timers->timers[u].time > next_time) {
result is:
if you put 2 or more functions to the timer list, it will only called one.
second one:
next_time should never < current time 
if is_relative = 0 and next_time = 0 and period = 1 then the timer function will called until next_time >= now without pause (now it was > 29000).

HCP24: bugfix: timer_add

---

include/civetweb.h
src/civetweb.c

This allows to put additional file meta data in your header fields

Added optional additional_headers for mg_send_mime_file

---

src/civetweb.c

This is the only way to safely call clock_gettime (that I know of) when compiling for OSX 10.12 or iOS 10.
Please review for correctness and whether or not this seems like a good fix from a code-style perspective. I'm not a fan of the `#define clock_gettime ...` solution, but I'm not sure there's a cleaner way other than modifying anywhere that clock_gettime is called.
Refs #349.

Second fix attempt for issue 349.

---

src/civetweb.c

Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>

discard unread data if handled by begin_request()

---

src/civetweb.c

Based on the value of the configurable auth_domain_check_enabled, we
validate whether a request with absolute urls matches the auth domain or
not.
Fixes #397 
Signed-off-by: Abhishek Lekshmanan <abhishek@suse.com>

make auth domain check optional via a configurable

---

.gitignore
examples/embedded_cpp/embedded_cpp.cpp

Fix build embedded_cpp.cpp

---

resources/cert/make_cert.bat

Otherwise, OpenSSL complains with the message "unable to write 'random state' "

Make sure make_cert.bat is executed with admin rights

---

src/civetweb.c
src/mod_lua.inl

Added background script parameters and shutdown detection

---

src/civetweb.c

Allows applications to internally use multiple civetweb instances.
Fixes: #527
Signed-off-by: Karol Mroz <kmroz@suse.de>

civetweb: setgid/groups/uid only once if needed

---

include/civetweb.h
src/civetweb.c

As discussed in 
https://github.com/civetweb/civetweb/issues/526 
here is the pull request for this enhancement.

Add new callback get_external_ssl_ctx

---

include/civetweb.h
src/civetweb.c

Result of #531 "Allow access to mg_connection.SSL"

Provide client peer certificate (X509) in mg_client_cert structure.

---

src/civetweb.c
src/mod_lua.inl

I still need it for Visual C++2010.

Restore C89/C90 compliance

---

src/civetweb.c

This allow to exploit caching also for mg_send_file family helpers.

Use caching consistently for static file requests.

---

CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

- Adding prefixes to variable names and targets
- Adding the ability to turn off the web server executable

Improving the ability to embed civetweb into a parent CMakeLists.txt

---

src/civetweb.c

This commit guarantees that the handler unregistered using
mg_set_request_handler() will not be called after
mg_set_request_handler() returns.
It prevents some kind of race condition between
mg_set_request_handler() and handler use in handle_request()
Signed-off-by: Herve Codina <Herve.CODINA@celad.com>

Avoid request handler call after unregistering

---

src/civetweb.c

https://randomascii.wordpress.com/2017/01/08/add-a-const-here-delete-a-const-there/

mg_option config_options[] - add const

---

CMakeLists.txt
src/civetweb.c

Various fixes to pass build errors on GCC and Visual Studio 2015.

Vs2015 warning fix

---

src/civetweb.c

This patch contains minor fixes to build on Windows Visual Studio 2015
without any warnings.
Signed-off-by: Keith Holman <keith.holman@windriver.com>

build: fixes for Visual Studio 2015

---

src/CMakeLists.txt

This patch updates the source tree to generate shared library.
Signed-off-by: Keith Holman <keith.holman@windriver.com>

build: add ability to generate shared library

---

Makefile
src/civetweb.c
src/main.c

I made a small patch to daemonize and write PID to /var/run/civetweb.pid.

Small patch for daemonize

---

src/civetweb.c

The SSL_Accept and SSL_Connect operations had a timeout of 2 seconds,
for slow and bad networks, this caused disconnects in the Connect and
Accept stages. This change allow the timeout to be reused to allow
SSL_Connect and SSL_Accept to be longer.

Reuse timeout for SSL Connect and Accept operation.

---

docs/api/mg_send_file_body.md

It seems that there is a small typo in the description!

Corrected typo in mg_send_file_body.md

---

include/CivetServer.h
src/CMakeLists.txt

The C++ DLL has to export their own symbols but to import symbols from C DLL.

Separate C and CXX DLL import and export flags

---

src/civetweb.c

Issue #708
For instance, SSL_connect() returns SSL_ERROR_WANT_READ two times or so.

Improve response time at sslize()

---

.gitignore
.travis.yml
CMakeLists.txt
appveyor.yml
conan/build.py
conan/test_package/CMakeLists.txt
conan/test_package/conanfile.py
conan/test_package/test_package.cpp
conan/travis/build.sh
conan/travis/install.sh
conanfile.py

Hi!
This PR is related to issue #712.
Here I list some important points in this PR:
- Travis CI jobs to build Civetweb as Conan package in Linux and Macos
- Appveyor jobs to build Civetweb as Conan package in Windows
- Add test package to validate the Conan package created
- Fix bad support for clang 4 (flto)
- Apply new Conan conventions from 1.8
Conan jobs will be executed **ONLY** for Github tags. Any other PR will not trigger a new job, otherwise your CI time will increase.
I've created a virtual tag in my fork to check that conditional:
https://github.com/uilianries/civetweb/tree/v1.12
https://travis-ci.com/uilianries/civetweb/jobs/167366381
https://ci.appveyor.com/project/uilianries/civetweb/builds/21266286
Conan uses the file conanfile.py as recipe to execute all steps necessary to …

Build Conan package in CI (#712 )

---

build

the build_type option is reversed

fix build type in build script

---

src/civetweb.c

For example, the following code causes buffer overflow.
```C
int bufsize = mg_get_system_info(NULL, 0);
char *buf = malloc(bufsize);
mg_get_system_info(buf, bufsize);
```
I know enough room for `mg_get_system_info()` in this case is `bufsize + 1`, but anyway the function
must not exceed `bufsize`, so I want to merge this request.
Before merging this, I want to confirm the purpose of `int reserved_len` variable. Did you intend to reserve space for a closing bracket ( "}\n" ) by using the variable in case the specified buffer did not have enough space ? If so, I need to modify the request a little.

Fix mg_get_{system|context|connection}_info()

---

src/civetweb.c

Minor fixes for SSL/TLS client code

SSL client fixes

---

src/civetweb.c
unittest/public_server.c

Although I have tested this as well as possible, I want your review.

Fix reading a message body

---

src/civetweb.c
src/mod_lua.inl
src/timer.inl
unittest/private.c

I have selected stack/context based approach for readability, though thread-local storage is available.
This request might conflict with the commit of https://github.com/civetweb/civetweb/issues/719#issuecomment-452594507 . I also agree to apply it.

Several fixes and improvements about threading

---

docs/UserManual.md
src/civetweb.c
src/mod_lua.inl

8454ab6afb8846b3a49f8d3f2614d2e573957e13 is optional. I'll drop it on demand.

Fix Lua connect()

---

docs/api/mg_form_data_handler.md

Added documentation for the field_get method and fixed formatting issues on the mg_form_data_handler.md page

mg_form_data_handler.md improved

---

docs/Building.md
src/civetweb.c
src/handle_form.inl

This contains the patches requested in the discussion in #764.

NO_FILESYSTEMS follow-up

---

src/civetweb.c

These are two small changes needed to compile civetweb with XCode 10.3

Fix compilation issues with Xcode 10.3

---

src/civetweb.c

No need to call discard_unread_request_data when conn->must_close is true

---

src/civetweb.c

https://github.com/civetweb/civetweb/issues/843

Support BoringSSL

---

src/civetweb.c

https://github.com/civetweb/civetweb/issues/843

Support BoringSSL: disable CONF_modules_unload() and ENGINE_cleanup()

---

include/CivetServer.h
src/CivetServer.cpp

I think it is better to avoid code clones from "civetweb.c" for maintainability. However, if you don't want, feel free to point out lines in this commit. I will revert them back.

Use more of civetweb.c functions in CivetServer

---

src/civetweb.c

No need to hurry for marge this. Please examine carefully.

Improving remove_dot_segments()

---

src/civetweb.c

Though such a situation is quite rare, anyway stack allocation should be enough in this case.

X509 struct leaks if malloc() failed

---

examples/embedded_c/embedded_c.c
include/civetweb.h
src/CivetServer.cpp
src/civetweb.c

I have checked these commits as well as possible, but if you have questions, please ask me anything before merging.
Currently I have no idea about handler removal from the handler itself (#800, #819, #834). Furthermore, I don't feel the necessity of it so far.

Fix about SSL context and locking

---

src/civetweb.c

There are also bugs about the closing of the DLLs which are not fixed in this commit. They are somewhat complicated, so I will work on them at a later date.

Fix about commit 8f621bdfcb8ce53f2d3edfcc6b67cf3c2d9c8ac4

---

docs/UserManual.md
src/civetweb.c

The content of this PR is mostly IPv6 related fixes and improvements.
#591 can be closed if this PR is merged.
I guess you might be a bit negative or low priority about implementing IPv6 ACL. However, from my experience, it is useful enough.

Support IPv6 ACL, and some fixes

---

src/civetweb.c

https://github.com/civetweb/civetweb/issues/853

Fix mg_connect_websocket_client_secure

---

src/civetweb.c
src/mod_mbedtls.inl

Like #912, but merge to a development branch, not the master branch
see also #839

civetweb support mbedtsl v2.16.2

---

include/civetweb.h
src/civetweb.c
src/mod_zlib.inl

This pull requests includes:
- minor fix for formatting of out-of-memory message
- a first, partial update for client-side websocket compression

Websocket compression client

---

docs/mbedtls.md

mbedtls.md update

---

src/main.c

Undefine printf for amalgamation build

Undefine printf after use

---

src/main.c

Windows Explorer sometimes crashes and restarts in some environments. When this happens, the tray icon of Civetweb disappears. This commit fixes the problem.
(A little difficult to explain in my words, please look at this.)

Restore tray icon after shell (explorer) restarts

---

src/mod_lua.inl

Fix invalid uuid() call in mod_lua.inl

---

src/mod_lua.inl

Fix oom url_encode() error msg

---

Makefile
VisualStudio/civetweb_lua/civetweb_lua.vcxproj
VisualStudio/civetweb_lua/civetweb_lua.vcxproj.filters
docs/mbedtls.md
format.bat
src/civetweb.c
src/mod_lua.inl
src/mod_mbedtls.inl
src/response.inl
unittest/public_server.c

Merge mbedtls branch into master branch

Merge mbedtls into master

---

docs/api/mg_send_chunk.md
docs/api/mg_send_digest_access_authentication_request.md
docs/api/mg_write.md

Signed-off-by: Lorenzo Canepa <paperino1983@gmail.com>

docs/api/ fix link to mg_printf md page

---

RELEASE_NOTES.md

docs: typos rectified in RELEASE_NOTES.md
Signed-off-by: Rajdeep Roy Chowdhury <rrajdeeproychowdhury@gmail.com>

docs: typos rectified in RELEASE_NOTES.md

---

examples/linux_ws_server_cpp/CMakeLists.txt
examples/linux_ws_server_cpp/README.md
examples/linux_ws_server_cpp/main.cc

websocket server cpp support Ubuntu and macOS

Add websocket server cpp example

---

src/civetweb.c

Signed-off-by: Lorenzo Canepa <paperino1983@gmail.com>

should fix *** CID 349582:  Null pointer dereferences  (REVERSE_INULL)

---

CMakeLists.txt

[cmake] let enable X DOM sockets

---

src/third_party/lua_struct.c

fix the vulnerability mentioned in https://github.com/civetweb/civetweb/issues/1234

fix Integer overflow

---

src/third_party/lua-5.2.4/src/ldebug.c

fix the vulnerability mentioned in https://github.com/civetweb/civetweb/issues/1235

fix the negation overflow

---

src/civetweb.c

The socket thread_shutdown_notification_socket must only be used for context type CONTEXT_SERVER.

Only poll thread_shutdown_notification_socket for server context

---

docs/api/mg_form_data_handler.md

docs: fix typo on mg_form_data_handler api docs

---

src/handle_form.inl

Fix comparison of integer expressions of different signedness warnings in `mg_handle_form_request()`. This warning is triggered when `-Wsign-compare` is used with a recent `gcc` version.

Fix variable signedness in handle_form.inl

---

Makefile
src/civetweb.c

This change add support for Civetweb on RTEMS.

rtems: Add support for RTEMS

---

docs/UserManual.md

Add description for optional port configuration added in #1186. Closes #1185

Update listening_ports documentation
