src/civetweb.c
No need to send 500 if connection closed. We may want to send other
responses in other cases (e.g., 400).
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
=> don't always send 500 if couldn't get request

src/civetweb.c
Calling setgroups() between setgid() and setuid().
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
=> call setgroups() to avoid supplemental group leakage

src/CivetServer.cpp
I had it happen multiple times, that the closeHandler is called while the context was still null (during the constructor of CivetServer), resulting in a segfault.
It's crude hack, but I wanted the bug to be known.
=> Call of handler before context save (C++ Wrapper)

src/civetweb.c
backend might not have read all data, we need to make sure we flush all
incoming data.
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
=> fast forward request data on completion of begin_callback()

src/civetweb.c
I setup a small CMake project file and built the project in Xcode. The Mach error prevented it from compiling (even `make build` on command line didn't work). The rest are warnings that we turn on by default for our projects
=> Fix clang errors and warnings with Xcode 6.2

include/CivetServer.h
Found one other error related to c++11/0x. - runtime_error being undefined.
I think the definition of std::runtime_error was only being brought in by the map include when the c++11/c++0x flag is set. (as c++11 map adds the at function which throws out_of_range type, defined in stdexcept, which also includes the definition for runtime_error).
This change just adds the stdexcept include containing runtime_error to ensure that the runtime_error type is known regardless of previous includes
=> Added stdexcept include for use of runtime_error exception

Makefile, src/civetweb.c
This pull request adds chunked encoding support to civetweb - allowing civetweb to stream content when the Transfer-Encoding is set to chunked in the headers sent through Civetweb.
This code has been used for over a year actively, though based off of the last Mongoose code released under MIT licensing prior to GPLing. I have moved the code modifications over to civetweb and tested it, all seems to work ok.
This also adds a small bugfix to the makefiles to restore ability to compile on a Mac.
This has been compiled and tested on Mac OS X 10.9.5 and Linux.
If you have any feedback, please let me know.
=> Chunked encoding support

src/civetweb.c
* When no content-length header is encountered and we're in a PUT or
POST request - restore prior behavior initializing content_len to -1
rather than 0. It was a rather innocuous error, but good to restore
prior behavior.
=> Fix erroneous merge error when starting request and no content-len set

src/mod_lua.inl
src/civetweb.c:5533:0:
src/mod_lua.inl: In function ‘mg_exec_lua_script’:
src/mod_lua.inl:1169:37: error: ISO C forbids conversion of object
pointer to function pointer type [-Wpedantic]
lua_pushcclosure(L, (lua_CFunction) exports[i + 1], 0);
^
This patch uses the POSIX.1-2003 workaround.
See linux.die.net/man/3/dlsym
=> Cannot cast Lua function pointer in standard C

Makefile
Small patch, just fixes compiling on OSX.
=> Only include -lrt if on Linux

include/CivetServer.h
I've noticed that the symbols are not exported for the C++ interface.
CIVETWEB_API was missing from the classes declarations.
=> Symbols export for the C++ Interface

src/civetweb.c
clang diagnostic ignored needed -W to work properly on OS X.
=> Fix compiler warning on OS X compile. 

src/civetweb.c
Neither AIX 5 or HPUX 11 define va_copy or have a thread name
function.  Move existing va_copy #define out of a windows-only block
so that it can apply to any platform that needs it.
The HPUX system headers mistakenly define socklen_t as a 64bit value
on Itanium, and has function prototypes with socklen_t when compiling
with _XOPEN_SOURCE.  However, the socket functions actually expect a
pointer to a 32bit value.  Passing address of socklen_t rather than
int results in zero data returned, missing client net address from
the accept() and general badness.  Fix by forcing a redef of socklen_t
to int when building on HPUX.
Signed-off-by: David Loffredo <loffredo@steptools.com>
=> AIX, HPUX, Solaris build fixes, socklen_t 64bit fix for HPUX

Makefile
Right now -fPIC is used for .dll and .so (dynamic linked option), we need to add -fPIC for static link option too, as it could be used in a library who is dynamic linked.
=> Add -fPIC for static linked library.

src/civetweb.c
This is something I fixed years ago when it was mongoose.  I am mystified how that change never made it into civetweb.
=> Fixed using CGI interpreters with spaces in the path.

src/civetweb.c
When reporting an error if parse_http_message were to fail, sending back user input as is to the client poses a security risk to browsers. I propose removing the string in the error reporting.
=> Minor change to civetweb.c

src/civetweb.c
cc -c -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DOSX -Iinclude  -DUSE_STACK_SIZE=102400 -DNDEBUG src/civetweb.c -o out/src/civetweb.o
src/civetweb.c:130:5: warning: no previous prototype for function 'clock_gettime' [-Wmissing-prototypes]
int clock_gettime(int clk_id, struct timespec *t)
^
1 warning generated.
=> Resolve Mac OS X 10.9 compilation warning

src/civetweb.c
Check glibc version to use "pthread_setname_np".
If glibc is less than 2.12, we use "prctl" on linux, and nothing for other Systemes. Else we use pthread_setname_np
=> check glibc version

src/civetweb.c, test/unit_test.c
- check ctx before use
- refactor ifdefs : to safely use pthread_setname_np we can only check the glibc's version, no need to check the system. In case of linux, if the glibc is too old, we can use the old prctl function. It's is maybe possible to do the same on other architectures, i didn't check.
- isolate variables used for the memory debugging
=> check, refactor, isolation

appveyor.yml
The mingw-builds downloads need to be flushed whenever the download script
changes. It used to use a python script but has changed to a batch script.
Part of #147.
=> Fix Appveyor Dependency

test/civetweb_check.h, test/private.c, test/public.c
This ports the tests from `unit_test.c` into the CTest and check test framework. It can be merged at any time as the tests will provide increased testing coverage under the CMake build system but I will attempt to port as many tests to this branch as possible before merge.
This shows how the unit tests use the provided [check assertions](http://check.sourceforge.net/doc/check_html/check_4.html#Convenience-Test-Functions) to provide good feedback from failed tests. For example, rather than using:
```
ASSERT(strcmp(ri.http_version, "1.1") == 0);
```
We can use:
```
ck_assert_str_eq("1.1", ri.http_version);
```
When the assertion fails, check prints both strings providing a simple and easy feedback method to resolve the issue.
If the issue #163 is resolved, this merge request will report …
=> Porting Unit Tests to CMake

test/private.c
This resolves a clang diagnostics warning due to parse_http_message
accepting 'char *' as it's first argument. Resolves the [build error](https://travis-ci.org/bel2125/civetweb/builds/70736423) introduced in #164
=> Pass a mutable string in unit test

CMakeLists.txt, appveyor.yml, build.cmd, mingw.cmd, src/CMakeLists.txt, test/CMakeLists.txt, test/civetweb_check.h, test/private.c
This branch does various things to fix up the build on Appveyor and Windows in general:
* It adds more output to the mingw download log
* It uploads the mingw download log as an artefact
* It uploads the CMake cache as an artefact
* It fixes up the tests by correcting the environment path and build symbols
=> Appveyor fix

appveyor.yml, test/CMakeLists.txt
This bumps up the MinGW to 5.1.0 on Appveyor. It also uses the powershell cmdlets to push the artefacts rather than the CLI as that seems to have intermittent bugs.
=> MinGW Version Bump

CMakeLists.txt, appveyor.yml, src/CMakeLists.txt, test/CMakeLists.txt
This branch caches the downloaded the third party code on the Appveyor platform. It seems that the main reason for Appveyor false positives is when downloads fail for external software. The more we can cache the better as the download for the cached files is _much_ faster.
=> Cache Appveyor built third party code

test/CMakeLists.txt, test/private.c
I've ported a couple of the simple tests from `unit_test.c`. Hopefully this PR should report that the coverage on coveralls has increased.
Also, I'm hoping that the Appveyor will reuse the cached MinGW compiler.
=> Port Unit Tests

src/civetweb.c
Websocket clients using Sec-WebSocket-Protocol refuse to connect to civetweb server. Error: "Expected a Sec-WebSocket-Protocol header"
The |Sec-WebSocket-Protocol| header field is used in the WebSocket opening handshake.  It is sent from the client to the server and back from the server to the client to confirm the subprotocol of the connection. This enables scripts to both select a subprotocol and be sure that the server agreed to serve that subprotocol.
The changed code will echo the Sec-webSocket-Protocol header to the client.
=> Support Sec-WebSocket-Protocol header tag

CMakeLists.txt
The flag is controlled with the CIVETWEB_ENABLE_SERVE_FILES and should be
set to NO to disable static file serving.
=> Adds the NO_FILES definition to the CMake build

test/CMakeLists.txt, test/main.c, test/private.c, test/shared.c, test/shared.h
Adds the `--test-dir` argument to the unit tests that allows the check unit tests to retrieve the location of the test folder via `get_test_directory` after `#include "shared.h"`
This is set by CMake to `CMAKE_CURRENT_SOURCE_DIR` which will always point to the location of the `test/CMakeLists.txt`
=> Test directory

include/civetweb.h, src/civetweb.c
Sometimes the client code generating a response takes time. Long running code can check that function to determine if the server is coming down and abort the long running process gracefully. Internally, it just returns the value of ctx->stop_flag to the caller.
=> added public mg_is_context_stopped() function

Makefile
Using Cygwin64, build fails when trying to compile for Windows 32-bit.
'windres' needs to be supplied "-F pe-i386" when building for 32-bit.
My compile commands are:
* rm -rf out/; make CC=i686-w64-mingw32-gcc COPT="-static" WINDRES_FLAGS="-F pe-i386"
* rm -rf out/; make CC=x86_64-w64-mingw32-gcc COPT="-static" WINDRES_FLAGS="-F pe-x86-64"
Regards,
Shantanu
=> Allow parameters to the resource compiler

src/civetweb.c
I was having issue with mg_upload with multiple files (in my case I was using two upload files with file size around 8MB each).  In my case the second file that get uploaded will have a bad md5sum compare to the original file (the first file uploaded properly everytime).  I believe the cause of this issue is due to the fact that mg_read() got called without the "len" variable being updated right afterward.  I have put in a simple fix by not calling mg_read when the boundary (the end of first file) is found.
I noticed there is an unit test for multiple files upload, but it is currently ifdef out so I didn't bother to put in the test for this change.
=> Fixed mg_upload() to work with multiple files.

src/civetweb.c
=> Fix redefinition of timespec in VS2015

include/CivetServer.h, src/CivetServer.cpp
Personally, I would think that using removeHandler() for both kinds of handlers would be nicer instead of having an extra function. What do you think?
=> Adding removeWebSocketHandler

src/civetweb.c
Seems when building on Mac OS X there was a bracket missing in memset. Also, included string.h a bit earlier as memset is defined there.
=> fixed os x build, added missing bracket.

examples/embedded_c/Makefile, examples/embedded_c/embedded_c.c
- The example states that the civetweb library has not been build with websocket support although it actually checks for Ipv6 support. 
- in case the civetweb library has not been build yet. The execution of 'make' in the embedded_c example fails because the civetweb library is built without IPv6 and Websocket support.
=> Adapt IPv6/Websocket building/checking in embedded_c example  

include/CivetServer.h, include/civetweb.h, src/CivetServer.cpp, src/civetweb.c
We had a use case where we needed to use an in-memory user database and also needed to use Basic authentication. Instead trying to work this custom function into the guts of the handle_request() function, we came up with the idea to put a hook in to implement our special authorization handling code. This could open the door for other authorization backends (i.e. ldap, mysql) without too much disruption.
The function signature looks exactly like the request_handler, so I reused that and changed is_websocket_handler to handler_type, which is an enum as there is now 3 types of handlers (request, websocket, authorization).
=> Add custom authorization handler

docs/Embedding.md
There is a minor typo in /docs/Embedding.md. Line 28:
- include/civetweb.c
Should be:
- include/civetweb.h
=> Correcting minor typo

src/civetweb.c
The worker_thread_run function will free the conn memory when it quits.
Freeing it in mg_close_connection frees it too early, causing a crash in
the worker_thread_run function as it reuses conn until the server quits
and asks the thread to quit.
=> Only free conn if in client context.

include/civetweb.h, src/civetweb.c
This allows sending files with a specified Content-Type instead of
relying on file name extension lookup.
Addresses #271
=> Add mg_send_mime_file.

test/public_server.c
The broken test was introduced in 54c6b08.
Closes #276.
=> Fix signed conversion error in a new CGI test.

.gitignore, src/civetweb.c
Hi,
The "Connection:" header can contain multiple entries. In my specific case, I'm handling a WebSocket connection with keep-alive (so, the header is "Connection: keep-alive, Upgrade" - at least when the websocket is opened from Firefox).
The current places that check for "keep-alive" in the "Connection" header do a string compare against the whole header.
So, this patch:
1) Adds a utility function for checking if a specific option is listed in a multi-option (comma-separated) header.
2) Modifies the next_option() function to strip leading and trailing whitespace from the option. As mentioned above, the Firefox-generated header has a space after the comma, and a brief glance at the RFC seems to say that's allowable anywhere between tokens. I have not analysed the code to see if other …
=> Fix the checking of 'keep-alive' connection flag.

src/civetweb.c
This reloads the certificate and ca certificate on every request. The goal is to provide functionality for short lived certificates. The functionality can be enabled with the config option "ssl_short_trust".
It's advised to keep the certificates stored on tmpfs on systems with high throughput because of the increased disk io.
Why Short-Lived Trust?
Certificate Revocation Lists (CRLs) and Online Certificate Status Protocol (OCSP) are great technologies for checking the current status of certificates. The problem with these technologies is, that they introduce both scale and management challenges in deployed cloud applications. Short-lived trust enables added security in such environments, since compromised keys are less valuable to an attacker.
=> Added certificate hot swap for use with short lived certificates

docs/UserManual.md, src/civetweb.c
A follow up for pull request #280 _(Added certificate hot swap for use with short lived certificates)_
The following improvements have been made:
* This version stats the cert / key pem file and checks if a new version is available and only reloads then.
* Fixed a threading issue while reloading the certificate.
* Added documentation for the `ssl_short_trust` option.
=> Improved certificate hot swap for use with short lived certificates

.travis.yml
A few small Travis changes.
I added the exclude to the first matrix, but it didn't work until I added it to the second, so I think the second matrix key was overwriting the first.
=> Exclude GCC from OS X

CMakeLists.txt
Apparently -mwindows flag doesn't produce an error for the way the current CMake code checks, so the flag gets added on OS X (Clang) but then this produces a warning during compilation.
=> Fix "argument unused during compilation"

include/civetweb.h, src/civetweb.c
My application embeds a Python interpreter. Python requires each thread to be initialized specifically for use with Python (see https://docs.python.org/3.5/c-api/init.html)
This pull request adds a new callback function that is called when a new worker thread is initialized.  
See [this dicussion on the google group](https://groups.google.com/forum/#!topic/civetweb/W-PqjC1pjes).
=> Adding a callback that is called when a new worker thread is initialized

include/CivetServer.h, src/CivetServer.cpp
Forgetting the memset when using the C++ constructor yields invalid pointers
=> Automatically initialize mg_callbacks to NULL in constructor

test/shared.c
This also more accurately only sets these definitions for MSVC.
=> Fix "Macro name is a reserved identifier" on OS X

Makefile.osx
I tested this by using the sample .lp script in the manual.
I also set resources/ssl_cert.pem as the `ssl_certificate` and confirmed SSL is working. So I imagine that's dynamically loading the OpenSSL library that is built-in to OS X, which is pretty old. Apple deprecated it a while ago and dropped the headers from the most recent SDK. Ideally, the OS X app should use the latest OpenSSL build and static compile it into the binary. I did get this working as a test, but it'd be more work to set it up for automation, as OpenSSL would need to be downloaded, and `makedepend` needs to be downloaded compiled as an OpenSSL build dependency as well. Then OpenSSL's Makefile needs to be modified to set the OS X minimum version to match what civetweb uses. If I ever get that functioning, we should …
=> Add Lua to OS X app

src/civetweb.c
`uri_len` update is needed after the process 1.2. or 1.3. of `handle_request()`.
=> Fix unexpected 301 response

src/civetweb.c
On Mac setsocketopt for linger throws invalid arguments error if socket already closed from client side but,its same does not happen in windows or linux.
This commit is add a check if already client has closed socket,then we will directly close the socket without linger.
Fixes #237
=> close socket without linger when connection already closed from client

src/civetweb.c
=> Do not define clock_gettime for OSX versions >= 10.12.

test/unit_test.c
Ifdef's out the testing of legacy mg_upload API
Update parse_port_string test for new API; include ip version
=> Unit test fixes for legacy and updated API's

src/civetweb.c
#367 introduced a bug:
During websocket handshake, when client offers multiple protocols, civetweb server should ignore whitespaces. Currently it fails to match any subprotocol except the first one because of spaces between commas and subprotocols.
=> bugfix - ignore leading whitespaces when matching websocket protocols

src/CMakeLists.txt, src/civetweb.c, src/main.c
Changed the name used on build to the c++ wrapper library to something more related to the project.
Made  some minor fixes to avoid build errors.
=> Changing c++ library name to 'civetweb-cpp'

docs/api/mg_exit_library.md
This needs to be done also elsewhere.
=> Fixing API docs links

docs/Building.md
Not having used Makefiles in a while, the docs where unclear to me on the usage of the PREFIX option.
Here is what I tried until I found the solution:
Trial 1: This is what I expected to work from reading the docs:
```
$ make build PREFIX=/opt/civetweb WITH_LUA=1 WITH_WEBSOCKET=1
$ make -n install
install -d -m 755  "/usr/local/share/doc/civetweb"
install -m 644 resources/itworks.html /usr/local/share/doc/civetweb/index.html
install -m 644 resources/civetweb_64x64.png /usr/local/share/doc/civetweb/
install -d -m 755  "/usr/local/etc"
install -m 644 resources/civetweb.conf  "/usr/local/etc/"
sed -i 's#^document_root.*$#document_root /usr/local/share/doc/civetweb#' "/usr/local/etc/civetweb.conf"
sed -i 's#^listening_ports.*$#listening_ports 8080#' "/usr/local/etc/civetweb.conf"
install -d …
```
=> Documentation: Clarified usage of PREFIX option for Makefile

src/CMakeLists.txt
Previsously the include of OpenSSL worked a little by accident (the
default /usr/include directory being there). On system where two versions
of OpenSSL can cohabite (for example FreeBSD), issues can occur in the
form of including one version (the one in /usr/include) and
linking against another (the one /usr/local/include|lib).
The issue can be reproduced on FreeBSD 11 with the openssl-devel package
installed. FindPackage(OpenSSL) recovers 1.1.0, with directories /usr/local/include|lib),
linkage is set to this version, but lack of proper include meant that the openssl lib from the
basesystem (1.0.2, header in /usr/include/) is used to try compiling.
=> fix include directory for openssl

docs/api/mg_callbacks.md
`end_request` signature was missing the `reply_status_code` param.
=> Fix callback doc

src/civetweb.c, src/handle_form.inl
I prefer to compile civetweb.c as C++, so I can share the same precompiled header with the rest of my code.  This used to work with Civetweb version 1.7.
I know civetweb.c is a C program, but I see no harm in enforcing the extra type safety and const correctness required for C++.
In Visual Studio 2015 this is Properties -> C++ -> Advanced -> Compile As, or /TP on the command line.
=> Allow compiling as C++.

src/mod_lua.inl
name is conn and not con.
broke compilation of `make lib WITH_CPP=1 WITH_LUA=1 WITH_WEBSOCKET=1`
=> fix compilation issue with LUA and websockets enabled

CMakeLists.txt, Makefile, src/civetweb.c
In case we want to support larger HTTP requests (e.g., S3 Object PUT
with large metadata), we need to increase this value. So, make it
configurable.
Signed-off-by: Henry Chang <henry_chang@bigtera.com>
=> Make MAX_REQUEST_SIZE configurable

include/CivetServer.h, src/CivetServer.cpp
When I'm using CivetServer.cpp, a usercontext variable in the class is useful....  nothing in the class references it, but it is publicly accessible.
If you think this should be done by other means (e.g. deriving a class), just close this request :).
=> Add general usercontext variable to CPP server

ci/travis/install_rocks.sh, ci/travis/lua_env.sh, ci/travis/run_ci_tests.sh, ci/travis/setup_lua.sh
"/bin/bash" is a Linuxism.  "/usr/bin/env bash" is portable.
=> Fix bash path in shebangs

CMakeLists.txt, src/CMakeLists.txt
This keeps previous functionality by having executable installation on by
default. It also tries to mitigate the ability to "screw it up" by only
allowing users that have made themselves advanced to disable installing
the executable.
See: https://cmake.org/cmake/help/v3.9/command/mark_as_advanced.html
Closes #505.
=> Allow disabling executable install.

README.md
I fixed README.md.
[link here](https://www.wired.com/2016/06/apple-os-x-dead-long-live-macos/)
For Apple changed the original name "Mac OS X" to "OS X" in 2012 and then to "macOS" in 2016.
In the document I think should be better to modify.
=> Fixed README.md "OSX->macOS"

src/civetweb.c
I think plain ASCII is the safest format for most compilers/editors.
=> Delete Byte Order Mark

src/civetweb.c
The pre-condition I commented on 9e66683be31eb2ded472e76564155a3a3b87f31b is currently always satisfied, so this is not a security fix.
=> Trivial cleanups

src/civetweb.c
The current behavior is different from what [UserManual.md]( https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#enable_auth_domain_check-yes ) says.
=> Fix enable_auth_domain_check

src/civetweb.c
The second 664d7af6eac17833c55fa18aadb1440bbcc496b0 is optional. If you don't want, I'll remove it.
For CJK languages, 260(MAX_PATH) bytes in UTF-8 are only 86 elements in wchar_t. Sometimes I suffer this limit.
=> Fix about PATH_MAX

src/civetweb.c
When C11 is available, use [`_Static_assert`](http://en.cppreference.com/w/c/language/_Static_assert).
Otherwise, if C++11 is available, use ['static_assert'](http://en.cppreference.com/w/cpp/language/static_assert).
Finally, fallback on the custom array-index based implementation.
=> #394: static_assert on Windows with Clang

src/civetweb.c, src/handle_form.inl
The logic is inverted here. If 'truncated' has been set to 'true' by mg_snprintf(), then it means the file path was too long.
=> Fix truncation check in (deprecated) mg_upload_field_found() function.

include/CivetServer.h, src/CivetServer.cpp
I'm using civetweb with JSON requests/responses, so I needed to access the response body directly. I know that the C API can handle it pretty well, but lately I've been using the C++ classes. And either I can't find it or there isn't a clear method to retrieve it.
So I added this small part of code. Since "connections" map is protected, I can access connection post data only by a static method.
I've used this for the several past weeks even in production. I honestly didn't run the C tests because this affects the C++ interface. Does it have test routines for this too?
Thanks!
=> Adds static method to get post data from CivetServer

src/CivetServer.cpp
The old method seems to break if post data is too large or has some strange chars. This one is more stable and C++ like.
=> Changed method getPostData from CivetServer to a more robust method

Makefile, README.md, RELEASE_NOTES.md, ci/test/README.md, docs/APIReference.md, docs/Embedding.md, docs/UserManual.md, docs/api/mg_callbacks.md, docs/api/mg_cry.md, docs/api/mg_get_header.md, docs/api/mg_get_option.md, docs/api/mg_get_request_info.md, docs/api/mg_get_response_info.md, docs/api/mg_get_server_ports.md, docs/api/mg_get_user_connection_data.md, docs/api/mg_get_valid_option_names.md, docs/api/mg_get_var2.md, docs/api/mg_handle_form_request.md, docs/api/mg_set_websocket_handler.md, docs/api/mg_start_thread.md, docs/api/mg_websocket_client_write.md, examples/_obsolete/ws_server/ws_server.c, examples/embedded_c/embedded_c.c, include/CivetServer.h, include/civetweb.h, src/civetweb.c, src/mod_lua.inl, test/html_esc.lua, unittest/public_func.c, unittest/public_server.c
Fixed misspellings found by [codespell](https://github.com/lucasdemarchi/codespell).
=> Fixed a lot of misspellings in source code and documentation

src/civetweb.c
I just started to embed this library into my project and noticed this required but superfluous include directive.  
I don't know if this include is needed in the near future so I just commented it out.
=> Comment (currently) superfluous include directive.

src/civetweb.c
When checking for configuring a socket, if the port option indicates that
a dual host socket should be used (single socket to receive traffic from
IPv4 and IPv6 addresses, e.g., `+80`), the IP version returned is 10. To
signal that a socket should be used by both versions, the IPV6_ONLY socket
option should be set to 0. Prior to this commit, `set_ports_option` looked
for an IP version equal to 6 to set the option to zero, but should be
looking for a version of 10.
=> Fixing configuration of ports for IPv4/IPv6 dual host sockets

src/civetweb.c
Please consider to pull this as a solution for the part of issue https://github.com/civetweb/civetweb/issues/278 related to missing _mkgmtime in msvcrt.dll on 32-bits machines.
=> Added replacement for timegm where _mkgmtime can be missing.

src/civetweb.c
Disable same kind of warning as for clang
=> Disable gcc warning with OpenSSL 1.1 SSL_CTX_set_info_callback() call

src/civetweb.c
Using pthread_setname_np requires a #define _GNU_SOURCE before including
pthread.h, or it will cause warnings about implicit function
declaration:
net/http/civetweb/civetweb.c:2701:8: warning:
implicit declaration of function 'pthread_setname_np' is invalid in C99
(void)pthread_setname_np(pthread_self(), threadName);
^
=> Fix warning about implicit function declaration in CivetWeb

src/civetweb.c
This defines enables extra features from glibc.
These features available also with other compilers (like clang).
=> Define _GNU_SOURCE not only with gcc

src/civetweb.c
Function abort_process is not defined unless USE_TIMERS is defined, and so the previous version would not compile.
=> Function abort_process is not defined unless we are using timers.

src/civetweb.c
Select does not work with descriptor numbers bigger than 1024.
It cause application fail, when get such descriptor number.
I suggest to use poll instead of select.
=> Wait for ready socket using poll instead of select

src/civetweb.c
Hi, 
If the sslize call fails for a new connection, then it is not cleaned up.  This leads to a file descriptor leak.
=> Make sure that if sslize fails, we close the socket

src/main.c, unittest/public_server.c
This patch contains additional warning fixes for Microsoft Visual Studio
2015 without any warnings.  Specifically, this patch addresses warnings
generated by the test executables.
Signed-off-by: Keith Holman <keith.holman@windriver.com>
=> build: warning fixes for test executables

src/CivetServer.cpp
getParam will ignore param in query_string when body not NULL
=> param can from query_string or body

src/main.c
Fixes
src/main.c:89:9: error: 'printf' macro redefined [-Werror,-Wmacro-redefined]
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> undefine macro before redefining

src/civetweb.c
Remove deprecated ERR_remove_state (since SSL 1.0) and ERR_remove_thread_state (since SSL 1.1)
Use "const SSL *" in callback function for SSL_CTX_set_info_callback
In SSL documentation examples callback defined without const specifier `void (*)(SSL *, int, int)`  See:
https://www.openssl.org/docs/man1.0.2/ssl/ssl.html
https://www.openssl.org/docs/man1.1.0/ssl/ssl.html
But in the source code const SSL is used `'void (*)(const SSL *, int, int)` See:
https://github.com/openssl/openssl/blob/1d97c8435171a7af575f73c526d79e1ef0ee5960/ssl/ssl.h#L1173
Problem about wrong documentation described, but not resolved:
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1147526
Wrong const cast ignored on C or can be suppressed by compiler flags.
But when compiled with modern C++ compiler, correct …
=> Fix several compilation problem with OpenSSL

include/civetweb.h, src/civetweb.c
`SSL_set_tlsext_host_name` must be called after context creation and before `SSL_connect`.
Therefore it required me to push the client options to `sslize`.
You can test this by connecting to any website running behind Cloudflare. Without setting the hostname the SSL connection will fail.
=> Add support for clientside SNI

CMakeLists.txt, src/civetweb.c
Do not try do disable it for gcc 4.8, which is still very popular
=> GCC warning -Wdate-time appeared first with gcc4.9

src/civetweb.c
On Mingw-w64, or on MSVC and `_WIN32_WINNT >= 0x0600`, struct pollfd is already defined in winsock2.h in spite of lacking poll(). I recommend avoiding the name.
=> Avoid redefinition of pollfd if HAVE_POLL is not set

docs/UserManual.md
Fixes some typos and changes some grammar in the user manual, just to make some bits flow better and make it easier to read.
=> Fix some typos and change some grammar in the user manual

src/civetweb.c
There is a memory leak in the get_request function when it calls the alloc_get_host function. The conn->host can contain a valid/existing hostname. This change makes sure that it is free'ed if it already has been set for a connection.
=> fixed memory leak in get_request when fetching the remote host

src/CivetServer.cpp
Fixes a valgrind issue by limiting the constructed string to the number of bytes read
=> Fix #686 CivetServer::getPostData valgrind UninitCondition

src/civetweb.c
If civetweb is used behind a reverse proxy (for example, using Apache as a Reverse Proxy with mod_proxy), the listing directory reports wrong file/dir urls.
Example:
I have a civetweb server that answers internally at: `http://127.0.0.1:8080`
Apache configuration:
```
<VirtualHost *:80>
ProxyPreserveHost On
ProxyPass /example http://127.0.0.1:8080/
ProxyPassReverse /example http://127.0.0.1:8080/
</VirtualHost>
```
In my browser I can call
`http://127.0.0.1/example/`
internally I am redirected to
`http://127.0.0.1:8080`
In this case, `request_info.local_uri` is equal to `/` (because it's the proxy that calls civetweb internally).
Suppose the root folder contains `test.txt `
if `request_info.local_uri` is placed in front of the links, I will get the link `/test.txt` which resolves into …
=> fix relative url in directory listing

CMakeLists.txt, cmake/civetweb-config.cmake.in, src/CMakeLists.txt
That patch adds exporting of the CMake targets for later consumption. If replaces the need to write a custom `FindCivetWeb.cmake` and makes instead the project describing itself.
I have not tested it on Windows, yet. But it's a start and better than noting.
=> Export CMake project

include/CivetServer.h, src/CivetServer.cpp
To be able to query port details like SSL.
I am not convinced by the naming though. If you have a better idea than ``getListeningPortsFull()``. I can change it.
**EDIT** By the way, why is the struct called ``mg_server_ports`` and not ``mg_server_port``?
=> CPP interface: Added getter for full port information

src/mod_lua.inl
dlfcn.h must be included to be able to use dlopen otherwise build will
fail on:
src/mod_lua.inl:2845:41: error: 'RTLD_LAZY' undeclared (first use in this function)
lib_handle_uuid = dlopen("libuuid.so", RTLD_LAZY);
Fixes:
- http://autobuild.buildroot.org/results/7a189f49c5a8b6f7b3d4c57cda5982adc65dbc19
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> modlua.ini: include dlfcn.h

src/civetweb.c
The macro ECONNRESET is not always defined (e.g. on Visual Studio 2008).
=> fix for visual studio 2008

src/civetweb.c
This changeset implements a partial fix for LSB, as described in issue #722. It solves the problem of missing symbols `pthread_setname_np` and `timegm`.
=> partial fix to support Linux Standard Base (LSB)

src/civetweb.c
Be more verbose about SSL connection error on client side.  This might
help user to figure out his error.
=> Log SSL error also on client connections

CMakeLists.txt
Fixes #733
I've maintained the existing behavior - LTO is enabled by default for the C++ wrapper only. Let me know if you'd like me to change it. It might be better to enable LTO by default only when building a shared library.
=> Make link time optimization optional

docs/APIReference.md, docs/Contribution.md, resources/jni/Android.mk
1. Typo fix.
2. Android.mk: "Always use Unix-style forward slashes (/) in build files. The build system does not handle Windows-style backslashes (\) properly." According to: https://developer.android.com/ndk/guides/android_mk?hl=en#local_src_files
3. Android.mk: add include path
=> Typo fix and Android.mk fix

resources/jni/Android.mk
1. Remove -O2 option (let ndk-build handle it)
2. Add WITH_DEBUG option (it's supposed to work, but I don't use/know if it's ok)
3. Add the WITH_* options
4. The following options I don't use/know if it works: WITH_LUA_SHARED, WITH_LUAJIT_SHARED, WITH_DUKTAPE_SHARED, SSL_LIB, CRYPTO_LIB
5. Not implemented the WITH_CPP option
I copied from the main Makefile, so it's likely to works the same.
=> Add the WITH_* options

src/civetweb.c
Use correct file name when printing error message after unsuccessful
call to SSL_CTX_use_certificate_chain_file().
=> Use correct name of file (certificate chain) in error message

docs/api/mg_get_context_info.md
=> Documentation: mg_get_context_info.md fixed typo

src/mod_lua.inl
lua_pushlightuserdata() pushes a value onto the Lua stack, which has to be popped. Otherwise the stack fills up with every websocket timer callback.
=> Fix Lua websocket stack overflow error

examples/embedded_c/embedded_c.c, src/civetweb.c, src/handle_form.inl
Hello @bel2125 
This is supposed to serve as the initial PR that will pave the way for the Zephyr RTOS target in civetweb. As you know from your discussion with @PiotrZierhoffer, we would like to start by providing a way of using civetweb without any support for filesystems.
We started by using this with the `embedded_c` sample
Please let us know what you think about it in general and how would you prefer us to approach the various issues.
Some cases that probably need special attention are:
*  We compiled the code with `-DMG_EXTERNAL_FUNCTION_mg_cry_internal_impl` and `-DMG_EXTERNAL_FUNCTION_log_access` because their default implementation depended on files. For test purposes we provided empty functions, but requiring users to do that does not seem like the best approach - maybe adding …
=> Add option to disable filesystems support

src/civetweb.c
This is often defined in various places, add a definition check to make
sure it is not already defined.
This will be needed for the Zephyr RTOS port.
=> Add ARRAY_SIZE definition check

CMakeLists.txt, src/civetweb.c, zephyr/module.yml
This PR adds support for Zephyr RTOS. It also adds some meta-files to make civetweb usable as an externally usable Zephyr module. It was tested on Sam E70 Xplained board.
Note that the work on the side of Zephyr is not really finished (see: https://github.com/zephyrproject-rtos/zephyr/pull/17019)
Here is the main issue that sums up the porting efforts on the side of Zephyr: https://github.com/zephyrproject-rtos/zephyr/issues/16683 - all the individual issues are referenced there.
Some of the changes here (for example the change from sscanf to atoi in one of the lines, or the way the stacks for worker threads are indexed for zephyr) can be removed once the Zephyr side is fully finished.
You can also see that lots of the includes have been moved around. This is to minimize slicing the code …
=> Zephyr RTOS port

src/civetweb.c
Includes for windows compilation. stdint.h was moved to global context since it was inclued at else condition of defined(_WIN32). Local definition of INT64_MAX was kept if the given include doesn't contain this definition.
=> Fix for Windows compilation

CMakeLists.txt
Zephyr runs cmake on every module it is provided, so we add filtering
not to build CivetWeb unless explicitly configured.
This, of course, only affects building within the Zephyr tree.
=> Add filtering for Zephyr buildsystem

resources/civetweb.conf, src/civetweb.c, unittest/private.c
Adds a configurable "max_connections" parameter that allows user-tuneable SOMAXCONN.
See-also:
https://github.com/civetweb/civetweb/issues/775
=> make SOMAXCONN configurable (fix 775)

src/civetweb.c
Change from "const char* const p" to "const char* p " due to syntax error on old VS versions (2010, 2012) on Continuous integration for Windows (AppVeyor).
=> Fix for double const on pointer

CMakeLists.txt
This prevents unneeded output and CMAKE settings to be set before we
move past the filtering.
=> Verify target platform earlier

docs/UserManual.md
I looked for ephemeral ports in the documentation, and because I somehow didn't think of using port 0, I started a PR to allow ephemeral ports, only to find that they are already supported (after changing the unit-tests for my PR). Maybe this helps other folks.
=> Document ephemeral ports.

src/CivetServer.cpp
Use `std::string::append` instead of creating `std::string` object for each append.
=> Optimize CivetServer::getPostData

.gitignore, docs/UserManual.md, src/civetweb.c
Solves #801
Add a config option for adding an arbitrary Cache-Control header to static file responses.
=> Add static_file_cache_control config option

src/civetweb.c
I am not sure how to construct the unit test for it to make it independent of the testing machine.
I think I'd either need to mock the getaddrinfo() response, have some control of /etc/hosts (or equivalent on WIN), or something completely different.
I'd appreciate any advice in this regard.
=> Fix hostname resolution in parse_port_string() (issue #822)

src/civetweb.c
Hi, I ran into an issue while using civetweb on Windows to host a server over https and the issue ended up being that civetweb was looking for the old OpenSSL (<=1.1.0) dlls. So I cloned civetweb and applied the following changes and recompiled with the OPENSSL_API_1_1 flag and it seemed to fix my problem. I thought it might be useful for others so I decided to make this pull request.
Please let me know if there are any changes I should make or potential concerns with it. Thank you.
Original commit message:
```
In OpenSSL 1.1.x, the following .dlls have new names:
libeay64.dll -> libcrypto-1_1-x64.dll
ssleay64.dll -> libssl-1_1-x64.dll
While work was done in https://github.com/civetweb/civetweb/issues/370
(commit 0733fae) to have civetweb use OpenSSL 1.1.x's new API, the
Windows .dll …
```
=> Use new .dll names on Windows x64 for OpenSSL 1.1.x

docs/Installing.md
Civetweb is available as a port in vcpkg, a C++ library manager that simplifies installation for civetweb and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build civetweb, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and here is what the port script looks like. We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

src/civetweb.c
It still defaults to `stdout` though. 
*Here is a proper pull request. I think my mistake was last time, that I commited to master after having created the pull request. So this time it's from its own branch.*
=> use DEBUG_TRACE_STREAM instead of stdout in DEBUG_TRACE_FUNC

src/civetweb.c
See the following TSAN report
```
WARNING: ThreadSanitizer: data race (pid=745240)
Read of size 8 at 0x7b08000006d8 by thread T1:
#0 master_thread_run civetweb/src/civetweb.c:18665:7 (objectbox-http-server-test+0x2781ec)
#1 master_thread civetweb/src/civetweb.c:18725:2 (objectbox-http-server-test+0x2781ec)
Previous write of size 8 at 0x7b08000006d8 by main thread:
#0 mg_start_thread_with_id civetweb/src/civetweb.c:6052:16 (objectbox-http-server-test+0x26ea67)
#1 mg_start2 civetweb/src/civetweb.c:19488:7 (objectbox-http-server-test+0x26ea67)
#2 mg_start civetweb/src/civetweb.c:19548:9 (objectbox-http-server-test+0x26ea67)
#3 CivetServer::CivetServer(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, …
```
=> Start master_thread after worker threads to avoid data race on worker_threadids

src/civetweb.c
This is Solaris 10 and gcc 5.5.50 from opencsw.
=> Need the timegm stub on Solaris

docs/api/mg_callbacks.md
https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L18083
The `init_thread` callback is passed `3` when the created thread is for websockets, 
but the documentation doesn't reflect this.
=> Update docs to reflect init_thread thread type for websocket

src/civetweb.c
Unless there is a particular reason, let's make symmetrical with x64 names.
=> Use new .dll names on Windows x86 for OpenSSL 1.1.x

unittest/shared.c
strncpy wouldn't append the null byte in case the source
string length is >= destination buffer.
's_test_directory' is already zero initialized. So leaving
the last byte alone is enough ensure the buffer is null byte
terminated in the worse case.
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
=> Fix a potential buffer overflow in unit test

src/civetweb.c
Build failed with MG_EXPERIMENTAL_INTERFACES without USE_SERVER_STATS and with NO_SSL
=> Fix to allow building without USE_SERVER_STATS

src/civetweb.c
I want to suggest "stop scan" feature for `scan_directory()`.
=> handle_directory_request() might leak memory

Makefile
cmd 'install' seems can not create symlink to the $(LIBDIR), so we turn to use 'ln' cmd directly.
=> Makefile: update install-slib target, symlink fix

src/civetweb.c, src/mod_zlib.inl
Here is a prototype pull request for #897.
A civetweb websocket server with this update can already successfully compress websocket traffic with Chrome, Firefox and Edge.
It's not production ready yet:
- codes has some hardcodes that need to be made more generic
- no tests included yet
Any comments & feedback are welcome, so I can further improve the pull request.
=> first prototype for websocket compression

CMakeLists.txt, cmake/civetweb-config.cmake.in, src/CMakeLists.txt
Hello,
I recently got a [report](jupp0r/prometheus-cpp#401) that CMake project import of civetweb fails in a MinGW environment. The root cause is that the exported civetweb config links against `WINSOCK::WINSOCK` which is unknown outside of the civetweb project.
This PR exports the publicly needed CMake find modules and looks those up on a case-by-case basis.
Thanks,
Gregor
=> fix: properly lookup winsock in imported project

src/civetweb.c, src/mod_mbedtls.inl
#839 
The Pull Request without  test.
I will try to compile and test the code, In the next few days.
As I said before,
the demo using compile option -DUSE_MBEDTLS and -DNO_SSL at the same time. NO_SSL is used to compile without OpenSSL. USE_MBEDTLS means that mbed TLS is compiled.
=> civetweb support mbedtls

include/CivetServer.h, src/CivetServer.cpp
The CivetHandler has been extended with overloaded handleGet, handlePut,
handlePatch ... functions with extra int *http_status argument.
This allows applications to return a valid HTTP status code if a resource is
not found or an operation is forbidden.
=> Added overload handle functions with http status

src/civetweb.c
I see the stop flag can be now optionally switched from volatile to atomic/lock protected :+1: 
However, adding the flag `-DSTOP_FLAG_NEEDS_LOCK` actually breaks the build:
```
...
src/civetweb.c:2898:19: warning: implicit declaration of function 'mg_atomic_add' is invalid in C99 [-Wimplicit-function-declaration]
stop_flag_t sf = mg_atomic_add(f, 0);
^
src/civetweb.c:2905:19: warning: implicit declaration of function 'mg_atomic_add' is invalid in C99 [-Wimplicit-function-declaration]
stop_flag_t sf = mg_atomic_add(f, 0);
^
src/civetweb.c:2914:8: warning: implicit declaration of function 'mg_atomic_compare_and_swap' is invalid in C99 [-Wimplicit-function-declaration]
sf = mg_atomic_compare_and_swap(f, *f, v);
^
...
```
=> Stop flag lock - fix missing functions

src/civetweb.c
This modification is successfully used in the context of the [WEBDAV server of Orthanc](https://book.orthanc-server.com/users/webdav.html) (DICOM server for medical imaging).
=> Adding HTTP methods for write access to files in WEBDAV

include/civetweb.h, src/civetweb.c
This changeset adds new function `mg_disable_connection_keep_alive()` to disable HTTP keep alive on a per-connection basis. Full context can be found in issue #727.
=> Added interface to disable keep_alive on a per-connection basis

CMakeLists.txt
case sensitive file fix if installing in UNIX like system (eg: Linux)
=> fix FindLibDl.cmake file name into the CMakeLists.txt

src/civetweb.c
Enable websockets support for Zephyr.
To use, pass `-DCIVETWEB_ENABLE_WEBSOCKETS=ON` to west.
Signed-off-by: Alexander Kozhinov <AlexanderKozhinov@yandex.com>
Signed-off-by: Piotr Zierhoffer <pzierhoffer@antmicro.com>
=> civetweb: WebSockets support for Zephyr

CMakeLists.txt
Sometimes one needs the CMake `Debug` build type
to select the Windows Debug runtime. But at the same
time the verbose logging output might be unwanted.
This PR adds the `CIVETWEB_ENABLE_DEBUG_TOOLS` option
to disable extensive logging and assertion.
=> CMake: Add option to disable Debug tools

Makefile
Added WITH_OPENSSL_API_1_0 and WITH_OPENSSL_1_1 to allow compiling against OpenSSL 1.0.x/1.1.x.  The default is still OpenSSL 1.1.x.
I couldn't compile against OpenSSL 1.0.x without modifying the Makefile so I added these two WITH's.
=> Support for OpenSSL 1.0.x/1.1.x

CMakeLists.txt, src/civetweb.c, src/mod_mbedtls.inl
There can be data remaining inside TLS layer so read them out before we poll a socket
=> mbedtls: read out unprocessed TLS data

src/mod_mbedtls.inl
failed mbed_ssl_handshake() was causing a leak because of
forgotten mbedtls_ssl_free call in a cleanup branch
=> fix memory leak in mbedtls support

src/civetweb.c
As mentioned in subject line, when building in debug for Mac using clang 11, the build fails with
Adding the include fixes the error
=> Fix for failing to build in Debug on Mac Big Sur (v11.2.1) using clang 11.0.0

include/civetweb.h, src/civetweb.c, src/mod_lua.inl
This PR is the successor of #964 (check there for further details). TL;DR: We need a dedicated buffer containing the raw (local) URI sent by the requestor. This is currently overwritten by some cleaning routine inside `civetweb`.
Motivations for my changes:
The memory used for `local_uri` propagates downwards a rather long way. It is set in `mg_get_response` (which is an external interface and never used inside `civetweb.c`):
https://github.com/civetweb/civetweb/blob/37300a0f09db4e6b64745d3b05ab5b2edc23497a/src/civetweb.c#L17910
or in `process_new_connection` which is the relevant part for now:
https://github.com/civetweb/civetweb/blob/37300a0f09db4e6b64745d3b05ab5b2edc23497a/src/civetweb.c#L18455-L18487
The `request_uri` originates from …
=> Add dedicated raw (local) URI variable

src/civetweb.c, src/openssl_dl.inl
This is a quick PR to support compiling with OpenSSL 3.0.
It is unclear if you want more OPENSSL_API defines like this or if you want to unify the code for 1.1 and 3.0 support under a separate define (like for example OPENSSL_API_1_1_PLUS) so I've created this PR so you can see what it looks like.
At this stage this is just testing compilation and getting your feedback on the approach you want used.
=> quick OpenSSL-3.0 API support

CMakeLists.txt
Hi,
Could the following simple change be reviewed please?
It will bump the minimum required CMake version to 2.8.12 now that it's released.
That will also avoid the following deprecation warning:
CMake Deprecation Warning at .../civetweb/CMakeLists.txt:2 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Thanks,
Gustavo
=> Bump minimum required CMake version

CMakeLists.txt, src/CMakeLists.txt
When building with Make, `WITH_ZLIB=1` can be used to enable compression with zlib, therefore this option should also be available when building with CMake.
=> CMake: add option for zlib support

docs/Embedding.md
Found a mistyped function call in the example section of the Embedding doc.
=> Mistyped function call in docs

src/handle_form.inl
Currently the buffered chunks fed to `mg_url_decode() ` may tear an encoded byte causing misinterpretation.
For example, "%42" is split on the buffer boundary into "%4" (which isn't recognized as a codepoint) and "2" and then recombined as "%42" instead of decoding. Things become even worse when unicode characters are present.
A more general and robust solution would be returning the number of bytes *actually* processed from mg_url_decode() but unfortunately I have no time to fix and test this in the whole project scope.
=> fix url-encoded payloads

src/civetweb.c, src/openssl_dl.inl
I had some problems using the NO_SSL_DL flag. Eventhough I was linking libcrypto in, then the code to load the library still was build.
I hope that I follow the conventions.
Solves: https://github.com/civetweb/civetweb/issues/1002
Signed-off-by: Kjeld Flarup <kfa@deif.com>
=> Fix using NO_SSL_DL

.gitignore, docs/APIReference.md, docs/api/mg_modify_passwords_file.md, docs/api/mg_modify_passwords_file_ha1.md, include/civetweb.h, src/civetweb.c
This new function makes it possible to add an entry to the password file without making the plain-text password known to civetweb (in fact, the caller may not even know it). Instead, the HA1 hash that's  stored in the password file is passed as a parameter directly.
=> Add mg_modify_passwords_file_ha1

Makefile
Fixed a typo in Makefile, this was causing 'make help' to fail
Signed-off-by: Girish Joshi <girish946@gmail.com>
=> Fixed a typo in Makefile, this was causing 'make help' to fail

src/civetweb.c
The function `ERR_remove_thread_state()` is deprecated since OpenSSL 1.1.0, and corresponds to an empty function. The macro `OPENSSL_REMOVE_THREAD_STATE()` is defined in `civetweb.c` as a no-op macro for OpenSSL 1.1.x, but this definition is missing in the case of the newly-released OpenSSL 3.x family, which causes an undefined symbol error while linking civetweb. This pull request introduces the missing definition.
=> missing definition of OPENSSL_REMOVE_THREAD_STATE if OpenSSL 3.x

src/civetweb.c, src/md5.inl
We (devolo AG) have rather strict requirements about source code passing static analysis (among other things, we require a good deal of SEI CERT compliance). This PR eliminates the following findings:
```
civetweb/src/civetweb.c:5942:22: warning: pointer parameter 'stop_flag' can be pointer to const [readability-non-const-parameter]
civetweb/src/civetweb.c:6172:13: warning: 'atof' used to convert a string to a floating-point value, but function will not report conversion errors; consider using 'strtod' instead [cert-err34-c]
civetweb/src/civetweb.c:6440:13: warning: 'atof' used to convert a string to a floating-point value, but function will not report conversion errors; consider using 'strtod' instead [cert-err34-c]
civetweb/src/civetweb.c:10816:21: warning: 'atof' used to convert a …
```
=> Fix static analysis findings

src/CMakeLists.txt
If host is iOS, executables need a BUNDLE DESTINATION, otherwise CMale configuration fails. It's easier to set DESTINATION globally if all targets of install() command are executables.
see https://cmake.org/cmake/help/latest/policy/CMP0006.html
=> CMake: fix installation of bundles on iOS/tvOS/watchOS

src/civetweb.c
If a client sends a request that isn't handled (like 'PROPPATCH /example.c HTTP/1.1') then 'is_valid_http_method()' is called before the HTTP version is parsed which means the response sent to the client is malformed ('HTTP/(null) 400 Bad Request'), so call 'is_valid_http_method()' after parsing the HTTP version.
There is still the possibility for the client to send complete garbage (like 'GARBAGE') then the 'HTTP/(null)' still appears, for this scenario we probably need to set the version to a default (like '1.0'), not sure though.
=> Fix for (null) in "Bad request" response

src/civetweb.c
"Unused parameter", "unused variable", and "cast to same type".
These findings occurred after compiling with MG_EXPERIMENTAL_INTERFACES.
=> Eliminate static checker findings in experimental interfaces

include/CivetServer.h
Found by the Clang `-Wdocumentation` warning.
=> Fix doxygen variable names

src/CivetServer.cpp
Otherwise I get the following warning:
```
'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct CivetCallbacks'
```
See: https://stackoverflow.com/questions/112085/is-this-c-structure-initialization-trick-safe
=> Replace memset by value-initialization

.github/workflows/cifuzz.yml
Signed-off-by: David Korczynski <david@adalogics.com>
This adds CI integration with CIFuzz. CIFuzz will run the Civetweb OSS-Fuzz fuzzers for a short period of time for each PR. The benefit is that regressions and bugs has a chance of being captured early in the development process.
=> ci: add cifuzz integration

src/main.c, src/md5.inl
Resolve compiler warnings with GCC 8.5.0 and Clang 13 (from CentOS 8):
* Avoid pointer subtraction with null pointers
* Remove unused `init` parameter of `mg_connect_client_impl`
* Improve `const`-ness of options
=> Resolve warnings

Makefile
While it's quite alright to use install to create directories, install
can do so on the fly using the `-D` parameter. Further more, install can
make installation easier when using the `-t` flag.
The combined set of changes makes it that the installation steps are now
idempotent, and do not fail anymore due to missing directories, such as
`install-headers`for example, which does not do the right thing if the
directory does not exists.
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
=> Makefile: Ensure each install is idempotent

src/civetweb.c
The `log_access` function uses the thread unsafe function `localtime`, replace with the re-entrant `localtime_r` when the `REENTRANT_TIME` flag is defined.
=> Replace usage of localtime with localtime_r in log_access when built with REENTRANT_TIME

CMakeLists.txt, cmake/civetweb-cpp.pc.in, cmake/civetweb.pc.in
add  pkg_check_modules() find lib
example
```
...
find_package(PkgConfig REQUIRED) # Ubuntu: sudo apt install pkg-config; macOS: brew install pkg-config
pkg_check_modules(Civetweb REQUIRED civetweb)
pkg_check_modules(Civetweb-cpp REQUIRED civetweb-cpp)
include_directories(
${Civetweb_INCLUDE_DIRS} # new, /usr/local/include
${Civetweb-cpp_INCLUDE_DIRS} # new, /usr/local/include 
)
link_directories(
${Civetweb_LIBRARY_DIRS} # new , /usr/local/lib 
${Civetweb-cpp_LIBRARY_DIRS} # new, /usr/local/lib 
)
target_link_libraries(${TARGET_NAME}
${Civetweb_LIBRARIES} # new, civetweb 
${Civetweb-cpp_LIBRARIES} # new, civetweb-cpp
)
...
```
=> feat: add pkg-config find libs

src/civetweb.c
Instead of using `#include <posix/unistd.h>`, just use `#include <unistd.h>`, etc.
Required-by zephyrproject-rtos/zephyr#43998
=> zephyr: remove posix prefix on standard headers

src/civetweb.c
This is to get rid of deprecation warninigs when building with newer
OpenSSL versions:
https://www.openssl.org/docs/manmaster/man3/SHA1_Init.html
=> Using higher-level wrapper of OpenSSL SHA1 hash function

src/civetweb.c
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.
=> zephyr: update include paths to use <zephyr/...>

src/civetweb.c
Remove unused variables that are set with no visible side effect.
/usr/bin/clang-14 -Wall -Wextra -Werror -Wshadow -Wno-sign-compare -Wno-pragmas -Wno-tautological-pointer-compare
Results in 
civetweb/src/civetweb.c:8769:12: error: unused variable 'mlen' [-Werror,-Wunused-variable]
size_t mlen = strlen(workdata->f_user)
^
civetweb/src/civetweb.c:14621:6: error: variable 'uri_len' set but not used [-Werror,-Wunused-but-set-variable]
int uri_len, ssl_index;
=> Remove unused variables mlen, uri_len

src/civetweb.c
Only starting from this SSL version one get deprecation warnings.
SHA1_Init’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
But one still can use old SHA methods with older SSL and with
systems without SSL at all
=> Use EVP_Digest only with OpenSSL 3.0

src/civetweb.c
Reverts civetweb/civetweb#1082
Variables are required for some #ifdef combinations.
These must be used as condition for removing the used/unused variables again.
=> Revert "Remove unused variables mlen, uri_len"

docs/README.md
at http://civetweb.github.io/civetweb/
=> Fix broken API documentation link

src/CivetServer.cpp
Gives CivetException a more defined error message by using `mg_start2()` and outputs errors in the exception message during construction.
=> Update CivetServer C++ Wrapper to use mg_start2

src/civetweb.c, unittest/public_server.c
Hurd also uses Mach.
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
```
#ifdef __MACH__
Some applications put Apple Darwin-specific code inside #ifdef __MACH__ guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by #if defined(__MACH__) && defined(__APPLE__)
```
=> Restrict overmatching MACH ifdef to only trigger on OSX and Mach

build
For systems where `sh` is not `bash`. Mentioned here earlier https://github.com/civetweb/civetweb/issues/200#issuecomment-142498907.
=> Use bash for pipefail in build script

src/civetweb.c, unittest/public_server.c
The authorization prompt for `PUT`/`DELETE` requests can be confusing for people not using the feature. Do not even ask for authorization on `PUT` and `DELETE` requests, if `PUT_DELETE_PASSWORDS_FILE` is not configured.
=> Do not try PUT/DELETE auth if not configured

src/civetweb.c
When unix socket is enabled, one gets several warnings like:
```
In function ‘sockaddr_to_string’,
inlined from ‘sockaddr_to_string’ at civetweb.c:3255:1,
inlined from ‘mg_cry_internal_impl.constprop’ at civetweb.c:3403:4:
civetweb.c:3296:26: warning: array subscript 50 is outside array bounds of ‘char[50]’ [-Warray-bounds]
3296 |                 buf[len] = 0;
```
It should be `buf[len-1] = 0;`
=> Fix compilation warning when USE_X_DOM_SOCKET is defined

src/civetweb.c
Change strncpy to mg_strlcpy and removed redundant NULL terminations.
Fix for #1114 and additional fixes.
=> mg_strlcpy fixes

src/civetweb.c
Added a very small fix for a typo of "APLN" (should be "ALPN").
=> Fix APLN typo

src/mod_mbedtls.inl
Fixes https://github.com/civetweb/civetweb/issues/1143
I tested with versions [v2.28.3](https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.4.0) and [v3.4.0](https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.4.0) which are both the most recent releases in the v2.x and v3.x release cycle.
=> Make mbedTLS module compatible with Mbed TLS v3.0.0+

src/mod_lua.inl
Currently, CivetWeb cannot be compiled with `USE_LUA` but without `USE_TIMERS` due to a syntax error. This error is fixed herein.
This has been hidden so far because of
https://github.com/civetweb/civetweb/blob/d7ba35bbb649209c66e582d5a0244ba988a15159/src/civetweb.c#L95-L97
I noticed this after realizing that `civetweb-timer` uses a lot more CPU time than all the `civetweb-workers` together:
and simply force-disabling `USE_TIMERS` caused compilation to fail. I meanwhile bandaid-fixed the issue be externally forcing `TIMER_RESOLUTION=1000` which should be good enough for the default timeout values.
=> Fix compilation of USE_LUA without USE_TIMERS

docs/api/mg_get_cookie.md
The current docs are a bit confusing, because `cookie` is not intended to be the name but the entire unparsed header that a variable shall be extracted from.
=> Fix mg_get_cookie() parameter description

src/CivetServer.cpp
Unlike C, where `= {0}` is universal zero initialization, in C++ code this pattern is regular field initialization and therefore emits:
```
missing field '...' initializer [-Wmissing-field-initializers]
```
[`= {}`](https://en.cppreference.com/w/cpp/language/zero_initialization) can be used, instead.
=> Fix -Wmissing-field-initializers in C++ code

src/main.c
This fixes the following
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
=> Fix compiler error with clang

src/civetweb.c
This pull-request fixes Issue #1163 by adding a socket-pair to the `mg_context`.
In particular, `mg_stop()` now calls `closesocket(ctx->user_shutdown_notification_socket)` immediately after setting the `stop_flag`, and the various calls to `mg_poll()` all now watch `ctx->thread_shutdown_notification_socket` for `POLLIN`, so that they will return immediately if/when the socketpair-connection is closed.
The result is that `mg_stop()` now reliably takes less than 20 milliseconds to return rather than up to 2000 milliseconds.
I suspect that with this change, `SOCKET_TIMEOUT_QUANTUM` could now be removed as unnecessary, but I didn't do that because I thought it might still have some other purpose outside of shutdown management.
=> Issue #1163: Performance issue: mg_stop() takes up to 2 seconds to return

src/civetweb.c
This pull request updates the `substitute_index_file()` function to work as expected even if the `index.html` file is present only in the fallback_root folder.  Previously if you had an `index.html` in the fallback-root but not in the primary-root, the `index.html` file would not get used when the user tried to load it implicitly (e.g. via `http://www.mywebsite.com/folder_name/`)
=> Update substitute_index_file() to look in the fallback-root if the index file isn't found in primary document-root

src/match.inl
These uses of offset 'i_pat' should follow the range check.
=> Fix offset used before range check

docs/Embedding.md, docs/UserManual.md, resources/civetweb.conf, src/civetweb.c, test/page3.ssjs, unittest/private.c
This pull request implements the performance enhancement described in issue #1169.
In particular, it modifies `civetweb.c` so instead of always creating N worker threads at startup, `mg_start()` simply records the specified maximum thread-pool size, and then whenever a request comes in over the network, `produce_socket()` will try to use an existing idle worker thread if one is available, otherwise it will demand-create a new worker thread and add it to the pool.  Once created, worker threads remain in the thread pool indefinitely, so in the worst-case scenario, the thread pool's size will eventually reach the number specified by the `num_threads` argument, but on a lightly-loaded server, we can often get by with a smaller number of worker threads.
Advantages to this behavior include:
1. …
=> Option to demand-create worker threads rather than always creating all of them inside mg_start()

src/civetweb.c
For CORS requests using authentication one need to add `Access-Control-Allow-Credentials` header.
Together with that header two other CORS headers should be provided  - `Access-Control-Allow-Headers` and `Access-Control-Allow-Methods`.
Also add `Access-Control-Expose-Headers` header. It is need for JavaScript applications which try to access some 'unsafe' fields in the http CORS response. For instance, one need it to get 'Accept-Ranges' value from the CORS response - while this header is not [listed as safe](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header)
=> Add support for more CORS headers

src/civetweb.c
For now, the connection is not closed at first keep_alive_timeout_ms interval, if the whole header can not be read in the second interval at one time, then return failed.
However, the http header can be transferred in two packages. Especially in https, there will be one byte exchanged before the real data transferring. This can lead to wrong header transferred timeout when two request are sended more than a keep_alive_timeout_ms interval.
=> Fix the wrong report of http header transferring timeout.

src/civetweb.c
This is my proposed implementation for CivetWeb issue #1185.  It extends the `parse_port_string()` function (and the `is_ssl_port_used()` function) to accept an additional port-suffix letter 'o' (either by itself, or before or after an 's' or an 'r').  Port numbers tagged with an 'o' work the same as without the tag, except that if the call to `bind()` fails, the `set_ports_option()` call will still return success as if they had succeeded, and therefore the CivetWeb process will launch as usual (except it won't be listening on the port it couldn't bind to, of course).
=> Added optional tag for ports in civetweb

CMakeLists.txt
pkgconfig files are arch dependend files so they needs to be installed in libdir.
=> install pkgconfig files in libdir

docs/OpenSSL.md
The current self-signed certificate doesn't work. It will cause an SSL error (EE_KEY_TOO_SMALL) when loading the PEM file.
=> Self-signed certificate key size from 1024 to 2048

src/mod_mbedtls.inl
The element `int state` in `struct mbedtls_ssl_context` is only available using the macro `MBEDTLS_PRIVATE(state)` for mbedTLS v3+. This was forgotten in https://github.com/civetweb/civetweb/pull/1144
=> Fix compiling CivetWeb + mbedTLS in DEBUG mode

src/civetweb.c
Back in July 2020, https://github.com/civetweb/civetweb/commit/688969fdddb431a7f0c729be66a51dd81fcba73e allowed all non-control characters in URLs to fix #894. However, this commit does not properly allow extended-ASCII characters due to checking `uri[i] < 33` where `uri` is a `signed char`. As consequence, everything beyond 127 will actually be considered to be negative and misinterpreted as control character in this check.
This issue was discovered when we saw that some `curl` versions send, e.g., Umlauts (`aöüß`) as they are (228, 246, 252, 223). To be clear, we are not talking about "ancient" versions here but, e.g., version 7.81.0 from last year which is shipped with many distros, a prime example being the current Ubuntu LTS.
Even more recent versions of `curl` (tested 7.88.0) seem …
=> Truly allow all non-control characters in URIs

docs/api/mg_request_info.md
Added missing underscore symbol to `remote_addr`.
=> fix minor typo in docs/api/mg_request_info.md

src/CMakeLists.txt
MbedTLS builds had two typos, one of them significant. This PR fixes both of them.
=> Fix building with MbedTLS

src/civetweb.c
Don't use fread() to read from CGI scripts because of possible buffering.
=> Fix for slow CGI

CMakeLists.txt
To correctly fill in the keyword fields "Version" in the pkg-config files section, you must specify the value of the "VERSION" option when calling the project() command
=> Add VERSION option to the project() command

CMakeLists.txt
Our call to `find_package(civetweb 1.16.0 EXACT CONFIG REQUIRED)` is failing with version 1.16 of civetweb installed via vcpkg. It appears that this is because `CIVETWEB_VERSION` is incorrectly set as `1.15.0` and therefore `civetweb-config-version.cmake` contains the wrong version. Consequently, there is no way to explicitly require version 1.16.0, because both 1.15.0 and 1.16.0 are the same version according to cmake.
=> Update CIVETWEB_VERSION to 1.16.0 in CMakeLists.txt

src/civetweb.c
Currently, trying to use civetweb as a submodule in a swift codebase cannot build on macOS due to the struct name `ah`. The fix is trivial, renaming the struct.
The changes in the PR rename the **struct** `ah` to `auth_header` and the **variable** in the codes related scope that `auth_header` to `ah`. Which can be seen as a better fit / following more common convetions for those symbols.
=> Rename ah struct to auth_header

src/civetweb.c
We are currently running into an issue trying to integrate civetweb as submodule and its reminder definitions creating interferences. 
https://github.com/civetweb/civetweb/blob/cd12e4737424fa9c266aaaf89909dcae617d2e51/src/civetweb.c#L1534-L1535
So I thought might fit to also disable the reminders when `NDEBUG` is defined, as they likely can be classified as debug info.
=> Disable `mg_` reminders when `NDEBUG` is defined

src/mod_lua.inl
See title. Currently, `master` cannot be built fully static on Alpine (`muslc` as `libc`) because of this.
=> Respect NO_DLOPEN also in Lua code

src/mod_lua.inl
Currently, this is broken for Lua server pages where, e.g., even 404 errors are served with HTTP 200 OK while they clearly shouldn't. When using error pages with Kepler syntax, this results in a situation that cannot even be recovered from the script itself as Kepler syntax doesn't allow sending custom headers.
How to reproduce: Define a custom error page using Lua, e.g., `error404.lp` and observe that it is served as `200 OK`. With this patch, the expected error code is returned as expected:
=> Send correct HTTP error code when serving custom error pages

src/mod_mbedtls.inl
This PR adds missing PSA (Platform Security Architecture) cryptography API initialization.
Calling `psa_crypto_init()` is mandatory when PSA is used which is, in turn, mandatory when using TLS 1.3 (`MBEDTLS_SSL_PROTO_TLS1_3`). When not being initialized, the server will finish startup but any encrypted traffic will cause errors deep inside the mbedTLS library (return code `0x6c00 == MBEDTLS_ERR_SSL_INTERNAL_ERROR`) and screens like:
With this change, TLS 1.3 works as expected with CivetWeb (current `master`) and mbedTLS (latest release, 3.6.0).
----
See https://github.com/Mbed-TLS/mbedtls/blob/v3.6.0/include/mbedtls/mbedtls_config.h#L1772-L1794:
``` c
/**
* \def MBEDTLS_SSL_PROTO_TLS1_3
*
* Enable support for TLS 1.3.
*
* \note See docs/architecture/tls13-support.md for a description of …
```
=> mbedTLS: Fix TLS 1.3 support

src/mod_lua.inl
The currently used code has `send_no_cache_header()` and `send_additional_header()` but NOT actually a call to `mg_response_header_send()`. So - when `NO_RESPONSE_BUFFERING` is unset (which is the default) - this merely adds the additional headers to the buffer but **does not send them**.
This causes headers added through the `additional_headers` config string to be ignored for Kepler LSP. Similarly, CORS and cache-control headers were missing in the same way.
This PR implements header handling of Lua Server Pages in the same way as done in many other places of CivetWeb.
=> Fix header generation for Lua Server Pages (Kepler syntax)

.github/dependabot.yml
Within the `.github` workflow, different actions are used. Most of them are pinned to outdated versions. This PR will add [Dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) to the repo which will run weekly and open PRs to keep the actions up-to-date.
=> Add dependabot to keep github-actions up-to-date

src/mod_lua.inl
This PR seeks fixing error reporting when handling Lua server pages.
Before, CivetWeb used [`lua_pcall(L, nargs, nresults, errfunc)`](https://www.lua.org/pil/25.2.html) with `errfunc = 1` when reporting errors. `errfunc = 1` specifies that the error handler is to be found on stack index 1 which seemingly isn't the case - at least, I have found no code ensuring that `mg.onerror` is exactly here and tests showed it is not.
Anyway, the result in my testing is an infinite loop of error reporting as the code always again reaches [this `goto`](https://github.com/lua/lua/blob/fd0e1f530d06340f99334b07d74e5133ce073787/ldo.c#L679) jumping back to [here](https://github.com/lua/lua/blob/fd0e1f530d06340f99334b07d74e5133ce073787/ldo.c#L654) eventually leading to a C stack overflow in Lua. Depending on …
=> Fix LUA error reporting

.github/workflows/cibuild.yml, unittest/public_server.c
I've added 2 tests using OpenSSL3.0 - one for Linux, one for macOS.
I also decided to drop OpenSSL1.0 tests - it's EOL since 2019 (!) and should not be used anymore. (The same is true of OpenSSL 1.1, but I did not want to go that far).
=> Add OpenSSL3.0 test and drop OpenSSL1.0 tests

src/civetweb.c
It was missed for websocket client. It's needed to perform ssl handshake successfully.
=> fix: missing host name for ssl

.github/workflows/cibuild.yml
Currently, the CI build uses `nproc` to get the number of available CPUs for using it with the `make -j` calls. However, on macOS, `nproc` is not available.
This PR adds a CI step which uses the right command on Linux and macOS to get the number of available CPUs to be used with `make`.
~~Additionally, a small bug with duplicated `shared` on macOS runners installing OpenSSL 1.0 was fixed.~~
=> Use all cores on macOS runners for CI build

src/civetweb.c
See [original issue](https://github.com/civetweb/civetweb/issues/1147).
From [OS X 11.1 and up](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes#Kernel), OS X provides a cache of `dylib` files, including a `libcrypto.dylib` shim that, unfortunately, yields a warning and an implicit `abort` call on loading. See dummy test using `lldb`:
```console
> cat dltest.c
#include <dlfcn.h>
int main(void) {
}
> make dltest
make: `dltest' is up to date.
> lldb dltest
(lldb) target create "dltest"
Current executable set to '/var/tmp/dltest/dltest' (arm64).
(lldb) b main
Breakpoint 1: where = dltest`main, address = 0x0000000100003fa0
(lldb) r
Process 52476 launched: '/var/tmp/dltest/dltest' (arm64)
Process 52476 stopped
* thread #1, queue = …
```
=> #1147 Load version-specific libcrypto and libssl shared libraries

CMakeLists.txt, examples/linux_ws_server_cpp/CMakeLists.txt
So that there are no [deprecation warnings](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings) on the latest CMake.
=> Bump minimum CMake version to 3.10

CMakeLists.txt, Makefile, README.md, docs/Building.md, docs/UserManual.md, docs/gnutls.md, format.bat, src/CMakeLists.txt, src/civetweb.c, src/mod_gnutls.inl
Add support for GnuTLS as an alternative to MbedTLS and OpenSSL. It closely follows the MbedTLS approach: The differences in civetweb.c are very small between the two versions. mod_gnutls.inl makes all the difference.
=> Add GnutTLS support.

docs/api/mg_server_port.md, include/civetweb.h, src/civetweb.c, unittest/public_server.c
There is no other way to know if binding to ports has succeeded. This is meaningful in the context of optional ports to check if the webserver is actually available on this port or not.
=> Expose if server ports are bound

fuzztest/fuzzmain.c
Hey, I noticed that this project is not fuzzed all that well in OSS-Fuzz. One simple reason is that libFuzzer discards inputs when returning a non-zero value and so gets stuck directly at the beginning for some targets. This PR just changes the returned value to 0. Additionally, this PR changes the server initialization to run in LLVMFuzzerInitialize to reduce the statefulness in the fuzz harness.
=> Update fuzz harness

src/civetweb.c
When users specify `[::]:80o` as port but the system has IPv6 disabled globally, e.g., with
```
GRUB_CMDLINE_LINUX="ipv6.disable=1"
```
then CivetWeb refuses to start even though it should skip the port if it cannot bind to it. However, when the port is specified as being optional, there is no point in treating non-availability of the protocol differently than the port already being taken. In this case, this port should simply be skipped.
=> Tolerate socket creation error if port is optional

src/civetweb.c
Terminate master_thread early when there are no listening sockets to prevent CivetWeb from crashing.
Fixes #1327
=>  Prevent crash on no bound ports

src/civetweb.c
Currently civetweb recognizes only a very limited number of MIME types.
While I'm sure the list may be extended significantly I'd like to contribute the MIME types that are commonly used to serve certificate (.crt, .cer) and CRL files (.crl).
Current behaviour is to serve certificate/CRL files with the default civetweb MIME type of "text/plain" which prevents browsers to correctly identify the served files.
See: [RFC-2585](https://datatracker.ietf.org/doc/html/rfc2585#section-4)
Add the following MIME types:
- application/pkix-cert
- application/pkix-crl
- application/x-pem-file
=> Add X509 certificate and CRL MIME-types

docs/OpenSSL.md, docs/gnutls.md
=> Use the correct Markdown syntax in page titles
